version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
    - 27017:27017
    
  library:
    build: .
    container_name: library
    ports:
    - 8089:8089
    depends_on:
    - mongodb