server:
  port: 8089

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: root
      #uri: mongodb://mongo_container:27017/library
      database: library
      authentication-database: library
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - logfile
          - prometheus
          - hystrix.stream
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
    hystrix:
      stream:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file: library_log.log