server:
  port: 8089

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: root
      database: library
      authentication-database: library
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - logfile
  endpoint:
    health:
      show-details: "ALWAYS"

logging:
  file: library_log.log